PDOK-14231
PDOK/sieve pull request #20
Opened 2022-07-06 06:11 UTC by DKKepinski

# Omschrijving

Als OZON wil ik uitgefilterde geometrieën geaggregeerd kunnen weergeven (POC)

geometrieen worden omgezet in POINT geom ipv verwijderd

https://dev.kadaster.nl/jira/browse/PDOK-14231

## Type verandering

- Nieuwe feature
- Verbetering oude feature
- Refactor
- Breaking change (opzet/werking veranderd)

# Checklist:

- [ ] Ik heb de code in deze PR zelf nogmaals nagekeken
- [ ] Ik heb mijn code beter achtergelaten dan dat ik het aantrof
- [ ] De code is leesbaar en de moeilijke onderdelen zijn voorzien van commentaar
- [ ] Ik heb de tests toegevoegd/uitgebreid indien nodig
- [ ] Ik heb de tests gedraaid die de werking van mijn wijziging bewijst
- [ ] De [PDOK documentatie](https://github.com/PDOK/interne-documentatie) is bijgewerkt indien nodig.
- [ ] Er zit geen gevoelig informatie in deze PR (wachtwoorden etc)

2022-07-06 07:18 UTC, roelarents commented on pkg/gpkg/gpkg.go
> +func (f *featureGPKG) IsReduced(isReduced bool) {
misschien `SetIsReduced` of `AddIsReduced`

2022-07-06 18:45 UTC, WouterVisscher commented
om maar te beginnen... volgende keer iets vriendelijker branch name....
dit wil ik nooit meer tegenkomen "PDOK-14231_Als_OZON_wil_ik_uitgefilterde_geometrieën_geaggregeerd_kunnen_weergeven_(POC)" 😄

2022-07-06 19:03 UTC, WouterVisscher commented
Als ik er nu zo over nadenk hebben we nu een sieve functie die "meer" doet dan alleen zeven.
Ik zou het zeven en vervangen graag terug zien in 2 aparte functies en die dan mogelijk te chainen met een channel
m.a.w. dat de solution van read->sieve->write dan iets kan worden als read->**replace**->sieve->write. Ook om op die manier te kijken/proberen of we de isReduced 'state' niet meer nodig hoeven te hebben.

m.b.t. de twpayne/go-geom package lijken er handige func() in te zitten, maar moeten we wel ff goed nadenken of we die **moeten** gebruiken of hoe we de bruikbare specifieke delen kunnen implementeren.

2022-07-06 19:07 UTC, WouterVisscher requested changes

2022-07-06 19:07 UTC, WouterVisscher commented on go.mod
> +require github.com/twpayne/go-geom v1.4.1
waarom een 2de spatial pkg?
is was go-spatial/geom niet voldoende?

2022-07-06 19:07 UTC, WouterVisscher commented on pkg/sieve.go
> +// getMultiPolygonCentroid returns Point with the centroid value of a multiPolygon
waar (behalve de test) wordt deze (getMultiPolygonCentroid) gebruikt?

2022-07-06 19:07 UTC, WouterVisscher commented on pkg/sieve.go
> +func makeCoord(point [2]float64) geometry.Coord {
hoe nodig is deze functie gezien die 1x maar wordt aangeroepen?

2022-07-06 19:07 UTC, WouterVisscher commented on pkg/sieve.go
> +		if sievedPolygon, b := polygonSieve(p, resolution); b == false {
(b== false) -> !b

2022-07-06 19:13 UTC, WouterVisscher commented
oja, voor z'n grote wijziging is het ook fijn als de README geupdate is (+voorbeeld)

2022-07-12 09:56 UTC, DKKepinski commented on go.mod
> +require github.com/twpayne/go-geom v1.4.1
ik heb de centroid berekening van de huidige als eerste geprobeerd, maar toen kreeg ik hele rare uitkomsten die ik niet kon verklaren. Infinity numbers, NaNs, hele hoge negatieve getallen (terwijl alle punten boven 0 waren) en als er een berekening uit kwam, dan klopte die niet. Na een dag proberen dacht ik even een ander pkg gebruiken, en die leverde wel output die ik verwacht (met als nadeel dat ik wat dingen moest doen om coordinaten om te zetten.

2022-07-12 10:03 UTC, DKKepinski commented
> om maar te beginnen... volgende keer iets vriendelijker branch name.... dit wil ik nooit meer tegenkomen "PDOK-14231_Als_OZON_wil_ik_uitgefilterde_geometrieën_geaggregeerd_kunnen_weergeven_(POC)" smile

haha, nja, het is wel makkelijk te herleiden naar jira ticket zo ;) maar ik ga nadenken over hoe dat in de toekomst beter kan



> Als ik er nu zo over nadenk hebben we nu een sieve functie die "meer" doet dan alleen zeven. Ik zou het zeven en vervangen graag terug zien in 2 aparte functies en die dan mogelijk te chainen met een channel m.a.w. dat de solution van read->sieve->write dan iets kan worden als read->**replace**->sieve->write. Ook om op die manier te kijken/proberen of we de isReduced 'state' niet meer nodig hoeven te hebben.
> 
> m.b.t. de twpayne/go-geom package lijken er handige func() in te zitten, maar moeten we wel ff goed nadenken of we die **moeten** gebruiken of hoe we de bruikbare specifieke delen kunnen implementeren.

dat is wat ik initieel wilde (sieve en replace functie los an elkaar), alleen dan zit ik met multipolygon die leunt op polygon sieve. omdat mp uit p bestaat, moet ik op dat punt al beslissen: weglaten of omzetten naar een punt.

het is mij niet helemaal duidelijk wat stap sieve in read-replace-sieve-write doet, we doen of weglaten of vervangen, maar dat is op basis van de berekeningen die in sieve functie gebeuren. 

moeten we niet een situatie hebben zo van read->moet_ik_iets_mee?-(ja)->moet_ik_weglaten_of_vervangen->dat_gene_doen->write?

2022-07-12 10:05 UTC, DKKepinski commented on pkg/sieve.go
> +// getMultiPolygonCentroid returns Point with the centroid value of a multiPolygon
ha, das inderdaad dubbel. die kan weg (opzet is paar keer gewijzigd)

2022-07-12 10:06 UTC, DKKepinski commented on pkg/sieve.go
> +func makeCoord(point [2]float64) geometry.Coord {
niet, maar ik dacht dat het leesbaarder zou zijn

2022-07-12 10:09 UTC, DKKepinski commented on pkg/sieve.go
> +		if sievedPolygon, b := polygonSieve(p, resolution); b == false {
fair, gefixed

2022-07-12 10:10 UTC, DKKepinski commented on pkg/gpkg/gpkg.go
> +func (f *featureGPKG) IsReduced(isReduced bool) {
goeie, gefixed

2022-07-12 10:12 UTC, DKKepinski commented
Nog over de isReduced state: ik dacht dat het wenselijk was om zichtbaar te maken dat iets aangepast is. Het was iig handig om te hebben voor het testen ;) 

Maar het leek mij ook netjes om te vermelden van "hey, deze informatie is bewerkt en niet 1-op-1 uit de data gehaald. Soort disclaimer eigenlijk

2022-08-15 12:35 UTC, roelarents commented on pkg/sieve.go
> +func multiPolygonSieve(mp geom.MultiPolygon, resolution float64) (geom.MultiPolygon, bool) {
kun je de return values namen geven? voor leesbaarheid en dan worden ze ook meteen geinitialiseerd

2022-08-15 12:35 UTC, roelarents commented on pkg/sieve.go
> +				if b {
een beetje verwarrend (voor mij) dat de `b` hier net omgedraaid is t.o.v. die bij polygon

2022-08-15 12:40 UTC, roelarents commented on pkg/sieve.go
> +					minArea := resolution * resolution
die kan minstens één regel omhoog

2022-09-16 15:29 UTC, RoelvandenBerg commented on pkg/sieve.go
> +		centroidCoord, err := xy.Centroid(polygon)
waarom de centroide van de polygoon? en niet van de bbox?

2025-07-30 12:34 UTC, RoelvandenBerg commented
Wont do

2025-07-30 12:34 UTC, closed without merging